# This site uses Nubia Jekyll Theme.
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Claudia Gerez-Miranda
logo:               # Logo image URL
description:        Documenting my journey as a marketing analyst.
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://nubia-jekyll.aspirethemes.com' # The base hostname & protocol for your site
linkedin: 	    https://www.linkedin.com/in/gerezmiranda/
github:             https://github.com/cgerezmi
facebook:           https://www.facebook.com/claudia.gerez.52
twitter:
instagram:


markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Claudia:
    name:     Claudia Gerez
    bio:      Chemical Engineer. Marketing Analyst. Data Scientist in the making.
    gravatar: https://secure.gravatar.com/avatar/ca7b3c0d266cf63182643ae134937b51
    email:    cgerezmiranda@gmail.com
    website:  http://claudiagerez.com
    linkedin: https://www.linkedin.com/in/gerezmiranda/
    github:   https://github.com/cgerezmi
